config/routes.rb
# frozen_string_literal: true

# Création des routes
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'lists/name'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root 'posts#index'

  # Routes pour les films
  resources :movies

  # Routes pour les listes
  resources :lists do
    # Routes bookmarks intégrées aux listes
    resources :bookmarks, only: %i[create destroy]
  end

  # Routes pour les bookmarks
  # resources :bookmarks, only: %i[index show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

# Validation du modèle Bookmarks
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6, message: 'Un commentaire doit avoir au moins 6 caractères.' }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'Ce marque-page a déjà été ajouté !' }
end

app/models/list.rb
# frozen_string_literal: true

# Validation du modèle List
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
# frozen_string_literal: true

# Validation du modèle Movie
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
  # validates :rating, numericality: {
  #   greater_than_or_equal_to: 0,
  #   less_than_or_equal_to: 10,
  #   message: 'Votre note doit être comprise entre 0 et 10'
  # }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

# Bookmark controller
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @review = Review.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

# Lists Controller
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

# Controller de Movies
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy]
  def index
    @movies = Movie.all
  end

  def show; end

  def new
    @movie = Movie.new
  end

  def edit; end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Le film a été créé avec succès'
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Le film a été mis à jour'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, notice: 'Film effacé avec succès.'
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: [list, Bookmark.new], local: true, html: { class: 'form-horizontal' }) do |form| %>
  <div class="form-group">
    <%= form.label :movie_id, 'Movie', class: 'form-label' %>
    <%= form.collection_select :movie_id, Movie.all, :id, :title, { prompt: 'Select Movie' }, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.label :comment, class: 'form-label' %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Add Bookmark', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container mt-5">
  <h1>Modier la liste</h1>

  <%= form_with(model: @list, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <% if @list.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Oops!</h4>
        <ul>
          <% @list.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-4">
      <%= form.label :nom, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.submit 'Valider', class: 'btn btn-primary' %>
      <%= link_to 'Retour', lists_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="container mt-5">
  <h1>Listes des catégories</h1>

  <%= link_to 'Nouvelle liste', new_list_path, class: 'btn btn-primary mb-3' %>

  <div class="list-group">
    <% @lists.each do |list| %>
      <a href="<%= list_path(list) %>" class="list-group-item list-group-item-action mb-3">
        <h5 class="mb-1"><%= list.name %></h5>
      </a>
      <div class="mb-4">
        <%= link_to 'Edit', edit_list_path(list), class: 'btn btn-warning btn-sm mx-1' %>
        <%= link_to 'Delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mx-1' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
  <h1>Nouvelle catégorie</h1>
    <%= form_with(model: @list, local: true, html: { class: 'form-horizontal' }) do |form| %>
      <% if @list.errors.any? %>
        <div class="alert alert-danger">
          <h4 class="alert-heading">Oops!</h4>
          <ul>
            <% @list.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mb-4">
        <%= form.label :nom, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit 'Create List', class: 'btn btn-primary' %>
        <%= link_to 'Back', lists_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mt-4 text-center">
  <h1>
    <%= @list.name %>
  </h1>

  <div class="container mt=4">
    <h2>Bookmarks</h2>
    <%= render @list.bookmarks %>
    <div class="d-flex justify-content-center">
      <div class="card mb-3" style="max-width: 100%, width: 800px;">
        <div class="row g-0">
          <div class="col md-4">
            <h3>Ajouter un signet</h3>
            <%= render 'bookmarks/form', list: @list %>
            <%= link_to 'Revenir en arrière', lists_paht, class: 'btn btn-secondary mt-3' %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true, html: { class: 'form' }) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h4>
      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :overview, class: 'form-label' %>
    <%= form.text_area :overview, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :poster_url, class: 'form-label' %>
    <%= form.text_field :poster_url, class: 'form-control' %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :rating, class: 'form-label' %>
    <%= form.number_field :rating, step: 0.1, class: 'form-control' %>
  </div>

  <div class="form-group mb-2">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="container mt-4">
  <h1>Edit Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Back', movies_path, class: 'btn btn-secondary mt-2' %>
</div>

app/views/movies/index.html.erb
<div class="container mt-5">
  <h1>Nos Films</h1>

  <%= link_to 'Nouveau film', new_movie_path, class: 'btn btn-primary mb-3' %>

  <div class="container">
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-md-4 mb-4">
          <div class="card">
            <% if movie.poster_url.present? %>
              <%= image_tag movie.poster_url, class: 'card-img-top', alt: movie.title %>
            <% else %>
              <img src="https://via.placeholder.com/300x450" class="card-img-top" alt="Placeholder Image">
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= movie.title %></h5>
              <p class="card-text"><%= truncate(movie.overview, length: 100) %></p>
              <p class="card-text"><small class="text-muted">Rating: <%= movie.rating %></small></p>
              <div class="card-body d-flex flex-column">
                <div class="d-flex justify-content-between">
                  <%= link_to 'Show', movie, class: 'btn btn-primary align-self-end' %>
                  <%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-secondary align-self-end' %>
                  <%= link_to 'Destroy', movie, method: :destroy, data: { confirm: 'Êtes-vous sûr(e) de vouloir supprimer ?' }, class: 'btn btn-danger align-self-end' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container mt-4">
  <h1> Nouveau film </h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Back', movies_path, class: 'btn btn-secondary' %>
</div>

app/views/movies/show.html.erb
<div class="container mt-4 text-center">
  <h1><%= @movie.title %></h1>

  <div class="container mt-4">
    <div class="d-flex justify-content-center">
      <div class="card mb-3" style="max-width: 100%; width: 800px;">
        <div class="row g-0">
          <div class="col-md-4">
            <% if @movie.poster_url.present? %>
              <%= image_tag @movie.poster_url, class: 'img-fluid', alt: @movie.title, style: "max-height: 100%; max-width: 100%;" %>
            <% else %>
              <img src="https://via.placeholder.com/300x450" class="img-fluid" alt="Placeholder" style="max-height: 100%; max-width: 100%;">
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <p class="card-text"><%= @movie.overview %></p>
              <p class="card-text"><small class="text-muted">Rating: <%= @movie.rating %></small></p>
              <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary' %>
              <%= link_to 'Destroy', @movie, method: :destroy, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <%= link_to 'Back', movies_path, class: 'btn btn-secondary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>